#![allow(dead_code)]
/* automatically generated by rust-bindgen 0.72.1 */

pub const PANEL: i32 = 1;
pub const PANEL_LISTBOX: i32 = 2;
pub const PANEL_QUITBUTTON: i32 = 3;
pub const PANEL_Y_OFFSET: i32 = 4;
pub const PANEL_X_OFFSET: i32 = 5;
pub const PANEL_SCALE: i32 = 6;
pub const PANEL_ROTATION: i32 = 7;
pub const PANEL_TEXTMSG_3: i32 = 8;
pub const PANEL_IMAGECTRL_ROT: i32 = 9;
pub const PANEL_TEXTMSG_2: i32 = 10;
pub const PANEL_TEXTMSG_4: i32 = 11;
pub const PANEL_IMAGECTRL_REG: i32 = 12;
pub const PANEL_IMAGECTRL_REF: i32 = 13;
pub const PANEL_TEXTMSG: i32 = 14;
pub const PANEL_PICTURE: i32 = 15;
